# Generated by Django 3.0.5 on 2020-04-18 00:05

from django.db import migrations, models
import onerApp.models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sold', models.BooleanField(default=False)),
                ('listed', models.BooleanField(default=False)),
                ('image', models.ImageField(default=None, upload_to='uploads/')),
                ('image_url', models.URLField(blank=True, default=None, null=True)),
                ('platformsListed', picklefield.fields.PickledObjectField(default=onerApp.models.Clothing.get_default_data, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClothingListings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listings', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
