# Generated by Django 3.0.5 on 2020-04-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='image',
            field=models.ImageField(default=None, upload_to='uploads/'),
        ),
    ]
