# Generated by Django 3.0.5 on 2020-04-16 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onerApp', '0002_clothing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='user',
        ),
    ]
