# Generated by Django 3.0.5 on 2020-04-16 00:15

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('onerApp', '0003_remove_clothing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='platformsListed',
            field=picklefield.fields.PickledObjectField(default={'Poshmark': False, 'StockX': False, 'eBay': False}, editable=False),
        ),
    ]
