# Generated by Django 3.0.5 on 2020-04-16 00:20

from django.db import migrations
import onerApp.models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('onerApp', '0004_clothing_platformslisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='platformsListed',
            field=picklefield.fields.PickledObjectField(default=onerApp.models.Clothing.get_default_data, editable=False),
        ),
    ]
