 export const GET_CLOTHES = 'GET_CLOTHES'
 export const DELETE_CLOTHES = 'DELETE_CLOTHES'
 export const ADD_CLOTHES = 'ADD_CLOTHES'
 export const SEARCH_CLOTHES = 'SEARCH_CLOTHES'
 export const GET_DATA = 'GET_DATA'
 export const REFRESH_DATA = 'REFRESH_DATA'